use_frameworks!

target 'DTPagerController_Example' do
  pod 'DTPagerController', :path => '../'

  target 'DTPagerController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
